### ISSUE TITLE
How to add a normal shader to the Tacto?

### ISSUE THREAD

**Issue by estellexky** [psodhi/tactile-in-hand#3]
Hello! Thanks for your excellent work. I would like to know how to add a normal shader to the Tacto just like you mentioned in your paper. 
Looking forward to your reply. Thanks.

**Comment by palomasodhi** [comment]
Hello, thanks for your interest! You can find the normal shader code on my fork of the tacto simulator here, https://github.com/psodhi/tacto/tree/normal_shader

**Comment by estellexky** [comment]
> Thank you very much!
